sudo: required
dist: trusty

language: go

go:
  - 1.8

python:
  - 2.7
  - 3.6

before_install:
  - sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  - sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  - mkdir $HOME/.virtuanenvs && echo "export WORKON_HOME=$HOME/.virtualenvs" >> $HOME/.bashrc
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update -qq 
  - sudo apt-get -y install python3-pip python-dev build-essential virtualenvwrapper openjdk-8-jdk maven dart
  - pip install -U setuptools virtualenv virtualenvwrapper
  - echo "source /etc/bash_completion.d/virtualenvwrapper" >> $HOME/.bashrc && source $HOME/.bashrc
  - cd $TRAVIS_BUILD_DIR/lib/python 
  - mkvirtualenv py2 && make deps-tornado deps-gae
  - mkvirtualenv py3 -p $(which python3) && make deps-asyncio


install:
  - go get github.com/tools/godep
  - cd $TRAVIS_BUILD_DIR && godep restore

script:
  - cd $TRAVIS_BUILD_DIR && godep go test ./test -race
  - cd $TRAVIS_BUILD_DIR/lib/go && godep go test -race
  - cd $TRAVIS_BUILD_DIR/lib/python 
  - workon py2 && make xunit-py2 flake8-py2
  - workon py3 && make xunit-py3 flake8-py3
  - cd $TRAVIS_BUILD_DIR/lib/java && mvn verify

notifications:
  email: false
